name: publish
on: [push]
jobs:
  build-and-copy:
    runs-on: node
    steps:
      - run: cd website
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn next export
      - run: cd ..
      - run: rm -rf docs
      - run: mv website/out docs
      - run: cd docs
      - run: touch .nojekyll
      - run: cd ..
      - run: git add .
      - run: git commit -m "Website build"
      - run: git push
